# Generated by Django 5.2.18 on 2026-10-06 21:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('conteudo', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='conteúdo')),
                ('publicada', models.BooleanField(default=False, verbose_name='publicada')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postagens', to='campaigns.campanha')),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postagens', to='organizations.ong')),
            ],
            options={
                'indexes': [models.Index(fields=['ong', 'publicada'], name='postagem_ong_publicada_idx')],
            },
        ),
    ]
