# Generated by Django 5.2.18 on 2026-10-06 21:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('descricao', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('item', 'Item'), ('horas', 'Horas')], max_length=8, verbose_name='tipo')),
                ('unidade', models.CharField(max_length=30, verbose_name='unidade')),
                ('meta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='meta')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_fim', models.DateField(verbose_name='data de fim')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativa', 'Ativa'), ('pausada', 'Pausada'), ('encerrada', 'Encerrada')], default='rascunho', max_length=9)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanhas', to='organizations.ong')),
            ],
            options={
                'indexes': [models.Index(fields=['ong', 'status'], name='campanha_ong_status_idx'), models.Index(fields=['tipo', 'status'], name='campanha_tipo_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('meta__gt', 0)), name='campanha_meta_positiva'), models.CheckConstraint(condition=models.Q(('data_fim__gte', models.F('data_inicio'))), name='campanha_datas_coerentes')],
            },
        ),
    ]
